# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 903cce75777b7a3cb11e3da2a04539d7b2d9b3fc509e17fff40de851bab6c88f74b710ca27f743e84ad56a90b10f4518f2895501f214608327113911f28296d7

test:
  secret_key_base: 914335d73768fc4e3b4bdf70924cbc153bf4e4d86e49a285568bff1d7b6187c7c978bdc9618ee9617aa029d0e7a5004a64493ece9428220a09bf2001152549ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
